### PR TITLE
relax elixir version

### PR DESCRIPTION
**Pull request by mitchellhenke**
Tests pass on Elixir 1.1.0 and 1.0.5. I also removed 1.0.0-rc1 if that's okay.

Thanks for the great library :)

### CODE REVIEW

**Comment by ericmj** [comment]
"1.0" is not a valid version requirement. Please set it to "~> 1.0".

**Comment by mitchellhenke** [comment]
Shoot, sorry about that, will fix it

**Comment by mitchellhenke** [comment]
updated it

**Comment by ericmj** [comment]
:heart:

**Comment by mitchellhenke** [comment]
Thank you!

**Pull request merged**
